"""watchlist strategy added

Revision ID: 16b65a93e41d
Revises: d2660efe0945
Create Date: 2023-01-21 13:11:10.909842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16b65a93e41d'
down_revision = 'd2660efe0945'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strategy_exchange', table_name='strategy')
    op.drop_column('strategy', 'exchange')
    op.add_column('watchlist', sa.Column('name', sa.String(length=15), nullable=True))
    op.create_index(op.f('ix_watchlist_name'), 'watchlist', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_name'), table_name='watchlist')
    op.drop_column('watchlist', 'name')
    op.add_column('strategy', sa.Column('exchange', mysql.VARCHAR(length=15), nullable=True))
    op.create_index('ix_strategy_exchange', 'strategy', ['exchange'], unique=False)
    # ### end Alembic commands ###
