"""watchlist strategy added

Revision ID: 1bd14ea85dd4
Revises: 16b65a93e41d
Create Date: 2023-01-21 13:34:08.111217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd14ea85dd4'
down_revision = '16b65a93e41d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
