"""watchlist strategy added

Revision ID: 283771919eaa
Revises: fda42c12abb9
Create Date: 2023-01-21 23:34:45.561070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '283771919eaa'
down_revision = 'fda42c12abb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('chat_id', sa.String(length=15), nullable=True))
    op.drop_constraint('watchlist_ibfk_2', 'watchlist', type_='foreignkey')
    op.create_foreign_key(None, 'watchlist', 'user', ['chat_id'], ['chat_id'])
    op.drop_column('watchlist', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('username', mysql.VARCHAR(length=15), nullable=True))
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.create_foreign_key('watchlist_ibfk_2', 'watchlist', 'user', ['username'], ['username'])
    op.drop_column('watchlist', 'chat_id')
    # ### end Alembic commands ###
