"""watchlist strategy added

Revision ID: 4f24f026c426
Revises: 9763f28a7328
Create Date: 2023-01-26 14:59:03.173284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f24f026c426'
down_revision = '9763f28a7328'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('watchlist_id', sa.Integer(), nullable=True))
    op.drop_constraint('recommendation_ibfk_1', 'recommendation', type_='foreignkey')
    op.create_foreign_key(None, 'recommendation', 'watchlist', ['watchlist_id'], ['id'])
    op.drop_column('recommendation', 'strategy_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('strategy_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recommendation', type_='foreignkey')
    op.create_foreign_key('recommendation_ibfk_1', 'recommendation', 'strategy', ['strategy_id'], ['id'])
    op.drop_column('recommendation', 'watchlist_id')
    # ### end Alembic commands ###
