"""create usermodel

Revision ID: 5ea6ca14760b
Revises: 5edb0e84c67b
Create Date: 2023-01-20 12:25:33.946917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea6ca14760b'
down_revision = '5edb0e84c67b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'plan', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'plan_id')
    # ### end Alembic commands ###
