"""create usermodel

Revision ID: 6734af24faa8
Revises: 5ea6ca14760b
Create Date: 2023-01-20 14:13:13.387568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6734af24faa8'
down_revision = '5ea6ca14760b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_chat_id', table_name='user')
    op.create_index(op.f('ix_user_chat_id'), 'user', ['chat_id'], unique=True)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=30), nullable=False))
    op.drop_index(op.f('ix_user_chat_id'), table_name='user')
    op.create_index('ix_user_chat_id', 'user', ['chat_id'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
