"""watchlist strategy added

Revision ID: 8f31f7038c73
Revises: 283771919eaa
Create Date: 2023-01-26 14:50:40.577618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f31f7038c73'
down_revision = '283771919eaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startegy', sa.String(length=15), nullable=True),
    sa.Column('asset', sa.String(length=12), nullable=True),
    sa.Column('timefarme', sa.String(length=12), nullable=True),
    sa.Column('signal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_asset'), 'recommendation', ['asset'], unique=False)
    op.create_index(op.f('ix_recommendation_close'), 'recommendation', ['close'], unique=False)
    op.create_index(op.f('ix_recommendation_high'), 'recommendation', ['high'], unique=False)
    op.create_index(op.f('ix_recommendation_id'), 'recommendation', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_low'), 'recommendation', ['low'], unique=False)
    op.create_index(op.f('ix_recommendation_open'), 'recommendation', ['open'], unique=False)
    op.create_index(op.f('ix_recommendation_startegy'), 'recommendation', ['startegy'], unique=False)
    op.create_index(op.f('ix_recommendation_timefarme'), 'recommendation', ['timefarme'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_timefarme'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_startegy'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_open'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_low'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_id'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_high'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_close'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_asset'), table_name='recommendation')
    op.drop_table('recommendation')
    # ### end Alembic commands ###
