"""watchlist strategy added

Revision ID: 9763f28a7328
Revises: a979f57eff8c
Create Date: 2023-01-26 14:57:18.003075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9763f28a7328'
down_revision = 'a979f57eff8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('strategy_id', sa.Integer(), nullable=True))
    op.drop_index('ix_recommendation_strategy', table_name='recommendation')
    op.create_foreign_key(None, 'recommendation', 'strategy', ['strategy_id'], ['id'])
    op.drop_column('recommendation', 'strategy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('strategy', mysql.VARCHAR(length=15), nullable=True))
    op.drop_constraint(None, 'recommendation', type_='foreignkey')
    op.create_index('ix_recommendation_strategy', 'recommendation', ['strategy'], unique=False)
    op.drop_column('recommendation', 'strategy_id')
    # ### end Alembic commands ###
