"""watchlist strategy added

Revision ID: d2660efe0945
Revises: a2280781b259
Create Date: 2023-01-21 12:51:02.040370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2660efe0945'
down_revision = 'a2280781b259'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('exchange', sa.String(length=15), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_description'), 'strategy', ['description'], unique=False)
    op.create_index(op.f('ix_strategy_exchange'), 'strategy', ['exchange'], unique=False)
    op.create_index(op.f('ix_strategy_id'), 'strategy', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_name'), 'strategy', ['name'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=True),
    sa.Column('asset', sa.String(length=15), nullable=True),
    sa.Column('exchange', sa.String(length=15), nullable=True),
    sa.Column('public_key', sa.String(length=60), nullable=False),
    sa.Column('secrete_key', sa.String(length=60), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_asset'), 'watchlist', ['asset'], unique=False)
    op.create_index(op.f('ix_watchlist_exchange'), 'watchlist', ['exchange'], unique=False)
    op.create_index(op.f('ix_watchlist_id'), 'watchlist', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_exchange'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_asset'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_strategy_name'), table_name='strategy')
    op.drop_index(op.f('ix_strategy_id'), table_name='strategy')
    op.drop_index(op.f('ix_strategy_exchange'), table_name='strategy')
    op.drop_index(op.f('ix_strategy_description'), table_name='strategy')
    op.drop_table('strategy')
    # ### end Alembic commands ###
