"""watchlist strategy added

Revision ID: da47cab603f7
Revises: 1bd14ea85dd4
Create Date: 2023-01-21 18:35:01.479931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da47cab603f7'
down_revision = '1bd14ea85dd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
